version: '3.8'

services:
  cna_user_api:
    image: zwad/cna_user_api:latest
    volumes:
      - ./database:/app/database
    environment:
      - JWT_SECRET= # <-- Add Secret here
    restart: unless-stopped
    ports:
      - "3000:3000"
