version: '3.8'

services:
  cna_user_api:
    image: zwad/cna_user_api:latest
    volumes:
      - db-data:/app/database
    environment:
      - JWT_SECRET= # <-- Add the JWT secret key here.
      - ALLOWED_ORIGINS=  # <-- List the allowed CORS origins here, separating multiple entries with a comma.
    restart: unless-stopped
    ports:
      - "3000:3000"
volumes:
  db-data:
