name: Build and Push Docker image

on:
  push:
    branches:
      - main
    paths:
      - 'src/**'
      - 'drizzle/**'
      - '.github/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      name: Set up QEMU
      uses: docker/setup-qemu-action@v3

      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        push: true
        tags: zwad/cna_user_api:latest